### ISSUE TITLE
Website URL???

### ISSUE THREAD

**Issue by Dhruvin-Purohit** [statch/gitbot#1]
Maybe add the website link to the README

**Comment by Dhruvin-Purohit** [comment]
#2 Fixes that^^

**Comment by itsmewulf** [comment]
Next time please add a [closing keyword](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) and assign yourself. Closing this since the PR in question was merged.
