### ISSUE TITLE
feat: discord forums -> github bridge

### ISSUE THREAD

**Issue by Ismoh** [statch/gitbot#283]
**Is your feature request related to a problem? Please describe.**
Is there a way to get discord forums updated to github issues?
Let's say gitbot will create an issue when discord forum post was created. And if someone creates a comment in discord, an issue comment will be created.

**Additional context**
Already discussed on [Discord](https://discord.com/channels/737430006271311913/781652773447794709/1113428154455953508).

**Comment by seven7ty** [comment]
It'll be some time until this is implemented, but I'll add it to the roadmap as it's a great idea.

**Comment by Ismoh** [comment]
Mhh?

**Comment by seven7ty** [comment]
Private matters have been keeping me from working on open source lately, when I have the time I'll try to get back to it.

**Comment by Ismoh** [comment]
No worries! I know that!
