### ISSUE TITLE
Better Gitlab Integration & Also Self Hosted

### ISSUE THREAD

**Issue by Josephrp** [statch/gitbot#376]
## Feature Request

- **Better Gitlab Integration & Also Self Hosted**

### Issue 

- the urls passed are being parsed for managed services for example Github and Gitlab. However self managed gits will have different urls.

### Solution

- parse the urls for `*.git`
- handle all url types gracefully 

### Alternatives and Additional Context 

- this should work for any `git` provider , not just self managed github / gitlab.

**Comment by seven7ty** [comment]
Hi there,
Do you mean just in the `lines` commands or overall site interop? If just lines, it's probably doable, though if you mean overall it's unfeasible due to the bot's dependence on the GitHub API.

**Comment by Josephrp** [comment]
i'll have to take a look at lines again, meanwhile there's native integration between gitlab and discord
