### ISSUE TITLE
Add support for translation? (Maybe add all text to a file and let people translate them!)

### ISSUE THREAD

**Issue by hellodhruvin** [statch/gitbot#43]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add support for translation of gitbot basically each server will have an ability to choose a language (out of current options.).
If their needed language is not found, we can basically ask them if they would be ready to translate?

**Describe alternatives you've considered**
Adding all text used in the bot to a JSON file for example a dir named locale with en.json and other languages that are in the bot.

**Additional context**
N/A

**Comment by seven7ty** [comment]
Very good idea! Though how I see it is that by default each user starts with english as their language, and if they want, they can change GitBot's locale (from available ones) according to their preference. So basically user-wide instead of guild-wide.

**Comment by hellodhruvin** [comment]
that'd also be cool as well

**Comment by seven7ty** [comment]
This is still being worked on in the [locale-update](https://github.com/statch/gitbot/tree/locale-update) branch
