### ISSUE TITLE
GitBot is down

### ISSUE THREAD

**Issue by PrenSJ2** [statch/gitbot#438]
**Describe the bug**
application does not respond

**To Reproduce**

1. add bot via link in readme
2. type /help
3. error

**Expected behavior**

no error

**Screenshots**
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/4798790c-a766-491b-9bae-e577cc74482a">
**Additional context**

**Comment by seven7ty** [comment]
Hi there,
The bot is currently down, and there's no concrete ETA on when it will be back up. Thanks in advance for your patience while I sort things out.

**Comment by gfargo** [comment]
Little curious, why not leave this issue open until the bot is back up online?

**Comment by franciscob1218** [comment]
Yeah like really, if this is closed then it indicates that there is no issue on first glance. Or u know you could update the readme to note there is a over all issue with the App? @seven7ty

**Comment by seven7ty** [comment]
My bad y'all. Hit the wrong button while commenting; reopening it for the time being.

**Comment by seven7ty** [comment]
GitBot is now alive and kicking again!
