### ISSUE TITLE
Remove parent message embed after GitBot's enhanced commit info is sent

### ISSUE THREAD

**Issue by bagusnl** [statch/gitbot#452]
**Is your feature request related to a problem? Please describe.**
Having both Discord's embed and GitBot's own commit/code info in the chat box can take a lot of space, most of time it's the whole window filled with those two.
![image](https://github.com/user-attachments/assets/ce2f4094-3919-4df1-867b-67f32c243e0b)
![image](https://github.com/user-attachments/assets/74039c40-9758-482f-84c9-c5286ee2e813)

**Describe the solution you'd like**
Remove any embeds from parent message after GitBot successfully sent enhanced commit/code info to the chat.

**Describe alternatives you've considered**
Manually removing the embed from parent message, which is quite tedious.

**Additional context**
None

**Comment by seven7ty** [comment]
Hi! I know this issue and remember thinking about it back when this feature was just being added, but sadly, there is not really an alternative. Discord handles embeds by allowing you to remove them through the edit message endpoint, and sadly, that is not available on messages that are not yours — not your message, not yours to edit — thus the bot can't touch a user's message. The only possible alternative would be deleting the original message afterward which, in my eyes, is not too great across the board.

**Comment by bagusnl** [comment]
I requested this since I know one of the bot that I use has this feature, though I don't know if its available with py but it's there (AFAIK) in DiscordJS

https://github.com/adryd325/discord-twitter-video-embeds/blob/main/src%2Fhandlers%2FreEmbed.js#L68

**Comment by seven7ty** [comment]
That's my bad. You're right; suppressing embeds is allowed even if the message isn't your own. 
Implemented it so that if the bot has the permissions required to manage messages it will automatically suppress the parent message embeds in https://github.com/statch/gitbot/commit/c90f94d80910521e2fa57d13aa17b586cdae263e

thanks a lot for your contribution!

**Comment by bagusnl** [comment]
**CRITICAL**

Regression happens after this feature is implemented where ALL EMBEDS gets removed, regardless if it gets processed by GitBot or not

**Comment by seven7ty** [comment]
Jeez, great catch! Thanks so much for pointing this out. I'm so far out of the development of GitBot neither did I notice this myself nor realize what I had done while implementing it (I forgot how the handlers are invoked in the event callback and did not bother to check...)

Complete blunder on my part, you saved the day! (https://github.com/statch/gitbot/commit/35da9244eae9900666b281fe03ec6b338d772dde)
