### ISSUE TITLE
Not working for some repos/orgs

### ISSUE THREAD

**Issue by ntaraujo** [statch/gitbot#53]
**Describe the bug**
Testing on my server, some repos are shown with `git repo {repo}` and others are not
Some orgs are shown with `git org {organization}` and others are not
The bot starts typing but after a few seconds it just stops.

**To Reproduce**
`git repo ntaraujo/killer`
`git repo ntaraujo/kivy-easier`
`git org kivy`
`git org pitao`

**Comment by seven7ty** [comment]
The issue was caused by the API returning blank `org['location']`  fields and is now resolved. Thanks for contributing!
