### ISSUE TITLE
Suggestion to Tweak the "commit" command

### ISSUE THREAD

**Issue by hellodhruvin** [statch/gitbot#59]
Maybe change the git commit command a bit and make it not create webhook if it does not have Manage Webhooks perms.

Overall only the text is necessary.

**Comment by hellodhruvin** [comment]
Also if the user doesn't have perm, just display text.

**Comment by seven7ty** [comment]
It's already there
![image](https://user-images.githubusercontent.com/63970738/117780867-52b24d00-b240-11eb-91c7-d884b6de3247.png)

**Comment by hellodhruvin** [comment]
You really Misunderstood the issue

If the bot does not have Manage Webhooks, just show them the text without doing the webhook URL.

**Comment by hellodhruvin** [comment]
And tell them in the embed's footer that webhook was not created as they/bot did not have permissions to do so.

**Comment by seven7ty** [comment]
Makes it slightly more confusing for the end-user, so for now I'm not going to add that
