### ISSUE TITLE
Looks like urls from "git repo -pulls" command are incorrect. 

### ISSUE THREAD

**Issue by CodingFeles** [statch/gitbot#70]
**Describe the bug**
Urls from `git repo -pulls` command are incorrect. 

For example: for PR with number 5, url will be:  
`https://github.com/use/repo/pulls/5` (take note at "pulls")
which will lead to pull requests list with filter "author:5", which will not yield desired result.

**To Reproduce**
Run `git repo -pulls` command and inspect generated urls.

**Expected behavior**
I suspect this url should've been  `https://github.com/use/repo/pull/5`, without **s**.

**Comment by seven7ty** [comment]
Hi, Nice catch! 🐛 
This has been resolved in 9768ee48f556451dc820498a7c309d0b5474a1a9 and 390a3359814d558258dd30171675994dc13a070a
